{{- include "stackgres.validatePasswords" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.initScripts.secretName }}
  labels:
    {{- include "stackgres.labels" . | nindent 4 }}
stringData:
  002-init-realtime-role.sql: |
    DO $$
    BEGIN
      IF NOT EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = 'realtime') THEN
          CREATE ROLE realtime WITH REPLICATION LOGIN PASSWORD {{ .Values.initScripts.passwords.realtime | squote }};
      END IF;
    END
    $$;
  003-init-platformdb-role.sql: |
    DO $$
    BEGIN
      IF NOT EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = 'platformdb') THEN
          CREATE ROLE platformdb WITH LOGIN PASSWORD {{ .Values.initScripts.passwords.platformdb | squote }};
      END IF;
    END
    $$;
  004-init-keycloak-role.sql: |
    DO $$
    BEGIN
      IF NOT EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = 'keycloak') THEN
          CREATE ROLE keycloak WITH LOGIN PASSWORD {{ .Values.initScripts.passwords.keycloak | squote }};
      END IF;
    END
    $$;
  006-init-platformdb-db.sql: |
    CREATE DATABASE platformdb WITH OWNER platformdb;
    CREATE DATABASE platform_ts WITH OWNER platformdb;
  007-init-realtime-db.sql: |
    CREATE DATABASE realtime WITH OWNER realtime;
  008-init-keycloak-db.sql: |
    CREATE DATABASE keycloak WITH OWNER keycloak;
  010-timescale-extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS postgis;
    CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
  014-init-realtime-extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS postgis;
  015-init-platformdb-extension.sql: |
    CREATE EXTENSION IF NOT EXISTS postgis;
  {{- if .Values.initScripts.passwords.airflow }}
  016-init-airflow-role.sql: |
    DO $$
    BEGIN
      IF NOT EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = 'airflow') THEN
          CREATE ROLE airflow WITH LOGIN PASSWORD {{ .Values.initScripts.passwords.airflow | squote }};
      END IF;
    END
    $$;
  017-create-airflow-db.sql: |
    CREATE DATABASE airflow WITH OWNER airflow;
  {{- end }}
  {{- if .Values.initScripts.passwords.geoportal }}
  018-init-geoportal-role.sql: |
    DO $$
    BEGIN
      IF NOT EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = 'geoportal') THEN
          CREATE ROLE geoportal WITH LOGIN PASSWORD {{ .Values.initScripts.passwords.geoportal | squote }};
      END IF;
    END
    $$;
  019-init-geoportal-db.sql: |
    CREATE DATABASE geoportal WITH OWNER geoportal;
    GRANT ALL PRIVILEGES ON DATABASE geoportal TO geoportal;
  020-init-geoportal-extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS postgis;
  {{- end }}
