import pytest

from jobs.sync.notification_processor.location_standarizer import LocationStandarizer
from schemas.entity_data_notification import (
    EntityAttr,
    EntityDataNotification,
)


@pytest.fixture
def standarizer():
    return LocationStandarizer()


class TestLocationStandarizer:

    @pytest.mark.parametrize(
        ("notification, updated_notification"),
        [
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [10, 20],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519174.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [10, 20],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519174.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
            ),
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitude",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519178.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [10, 20],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519174.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitude",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519178.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 2],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519178.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
            ),
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="r_eg25lon",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519174.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="r_eg25lat",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [10, 20],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519174.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="r_eg25lon",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519174.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="r_eg25lat",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [10, 20],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519174.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
            ),
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="r_eg25lon",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519272.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="longitudeLocation",
                            value=10,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="r_eg25lat",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=3,
                            type="Property",
                            units="",
                            timestamp=1607519492.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [10, 20],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="r_eg25lon",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519272.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="longitudeLocation",
                            value=10,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="r_eg25lat",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=3,
                            type="Property",
                            units="",
                            timestamp=1607519492.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 3],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519492.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
            ),
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 2],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 2],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
                ),
                (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519179.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519175.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 2],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519179.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="latitudeLocation",
                            value=2,
                            type="Property",
                            units="",
                            timestamp=1607519175.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 2],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
            ),
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 2],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="longitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 2],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
            ),
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="latitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 2],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="Device",
                    data=[
                        EntityAttr(
                            name="latitudeLocation",
                            value=1,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                        EntityAttr(
                            name="location",
                            value={
                                "type": "Point",
                                "coordinates": [1, 2],
                            },
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=None,
                        ),
                    ],
                ),
            ),
        ],
    )
    def test_location_standarization(
        self,
        notification: EntityDataNotification,
        updated_notification: EntityDataNotification,
        standarizer: LocationStandarizer,
    ):
        assert standarizer.process(notification) == updated_notification
