import pytest
from jobs.sync.notification_processor.timestamp_shifter import TimestampShifter
from schemas.entity_data_notification import EntityAttr, EntityDataNotification


@pytest.fixture
def timestamp_shifter():
    return TimestampShifter(offset_percent=0.25, datamodel_filter=["CrowdFlowEvent"])


class TestTimestampShifter:

    @pytest.mark.parametrize(
        "notification, updated_notification",
        [
            # CASE 1: 1 offset
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=False,
                        ),
                    ],
                ),
            ),
            # CASE 2: offset only in one attr
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519171.0,
                            timestamp_override=False,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519171.0,
                            timestamp_override=False,
                        ),
                    ],
                ),
            ),
            # CASE 3: offset only in one attr (by override)
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=True,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519173.0,
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=True,
                        ),
                    ],
                ),
            ),
            # CASE 4: because of override
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=True,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=True,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=True,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=True,
                        ),
                    ],
                ),
            ),
            # CASE 5: ignore datamodel
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="SomeOtherDatamodel",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="SomeOtherDatamodel",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="name",
                            value="FlowName",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                    ],
                ),
            ),
            # CASE 6: NEW - ignore because of rw_cfe_enable attribute
            (
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,  # This timestamp would normally be shifted
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="r_cfe_block", # This attr should cause the shifter to do nothing
                            value=True,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                    ],
                ),
                EntityDataNotification(
                    urn="urn:ngsi-ld:Device:TestDevice001",
                    tenant="pid",
                    scope="/",
                    type="CrowdFlowEvent",
                    notified_at=1607519176.0,
                    data=[
                        EntityAttr(
                            name="visitorId",
                            value="SomeId",
                            type="Property",
                            units="",
                            timestamp=1607519172.0,  # The timestamp should NOT be shifted
                            timestamp_override=False,
                        ),
                        EntityAttr(
                            name="r_cfe_block",
                            value=True,
                            type="Property",
                            units="",
                            timestamp=1607519172.0,
                            timestamp_override=False,
                        ),
                    ],
                ),  
            ),
        ],
    )
    def test_timestamp_shifter(
        self,
        notification: EntityDataNotification,
        updated_notification: EntityDataNotification,
        timestamp_shifter: TimestampShifter,
    ):
        assert timestamp_shifter.process(notification) == updated_notification
