# Generated by scripts/generate-env.sh for environment: ${PROJECT_NAME}
# DO NOT COMMIT — contains generated secrets.
# OPTIONAL component. Only rendered when APISIX_ENABLED=true in config.env.
# Deploy into the pid-gijon namespace (after `helm dependency update charts/apisix`):
#   helm upgrade --install apisix charts/apisix -n pid-gijon \
#     -f environments/${PROJECT_NAME}/apisix.values.yaml --wait
#
# NOTE: keycloak.clientSecret is the SAME value as web-back's KEYCLOAK_CLIENT_SECRET
# and is filled in after the one-time Keycloak realm setup (docs/06-post-install.md).

fiware:
  namespace: pid-gijon
  backend:
    # Mismo valor que API_GATEWAY_SECRET del backend: APISIX lo envia en
    # X-Gateway-Secret y PermissionController lo compara con hash_equals
    # (GDTIS-PT01-SEC-028/031). El chart aborta si queda vacio.
    gatewaySecret: "${API_GATEWAY_SECRET}"

keycloak:
  clientId: laravel-backend
  clientSecret: "${KEYCLOAK_CLIENT_SECRET}"
  realm: "${KEYCLOAK_REALM}"
  discoveryUrl: "https://${DOMAIN_KEYCLOAK}/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration"

gatewayAPI:
  enabled: true
  gateway: "${GATEWAY_PUBLIC}"
  gatewayNamespace: "${GATEWAY_NAMESPACE}"
  httpsOnly: true
  hostnames:
    - "${DOMAIN_APISIX}"

apisix:
  apisix:
    admin:
      credentials:
        admin: "${APISIX_ADMIN_KEY}"
  ingress-controller:
    gatewayProxy:
      provider:
        controlPlane:
          auth:
            adminKey:
              value: "${APISIX_ADMIN_KEY}"
