# Generated by scripts/generate-env.sh for environment: ${PROJECT_NAME}
# DO NOT COMMIT — contains generated credentials.
# Only rendered when STORAGE_TYPE=local.
minio:
  mode: standalone
  rootUser: "minioroot"
  rootPassword: "${MINIO_ROOT_PASSWORD}"
  users:
    - accessKey: "${MINIO_ACCESS_KEY}"
      secretKey: "${MINIO_SECRET_KEY}"
      policy: readwrite
  buckets:
    - name: "${S3_BUCKET}"
      policy: none
      purge: false
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  environment:
    MINIO_REGION: "${S3_REGION}"
    MINIO_PROMETHEUS_AUTH_TYPE: "public"
