# Generated by scripts/generate-env.sh for environment: ${PROJECT_NAME}
# DO NOT COMMIT — contains generated passwords.
replicaCount: 1
persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

credentials:
  username: "${MONGO_USER}"
  password: "${MONGO_PASSWORD}"
