# Generated by scripts/generate-env.sh for environment: ${PROJECT_NAME}
# DO NOT COMMIT — contains generated secrets.
# Overlay for charts/pid-gijon-core. Deploy with:
#   helm upgrade --install pid-gijon charts/pid-gijon-core -n pid-gijon \
#     -f environments/${PROJECT_NAME}/pid-gijon-core.values.yaml
#
# NOTE: KEYCLOAK_PUBLIC_KEY and KEYCLOAK_CLIENT_SECRET are filled in after the
# one-time Keycloak realm setup (see docs/06-post-install.md), which is also why
# web-back is enabled last.

global:
  imageRegistry: "${IMAGE_REGISTRY}"
  environment: "${ENVIRONMENT}"

gateway:
  enabled: true
  namespace: "${GATEWAY_NAMESPACE}"
  httpsSectionName: https

secretsStrategy:
  type: values

components:

  aetherLink:
    image:
      tag: "${TAG_AETHER_LINK}"
    config:
      CONTEXT_URL: "${CONTEXT_URL}"
      PLATFORM_TS_DB_HOST: "${PG_HOST}"
      PLATFORM_TS_DB_NAME: platform_ts
      PLATFORM_TS_DB_PORT: "${PG_PORT}"
    secrets:
      PLATFORM_TS_DB_USER: platformdb
      PLATFORM_TS_DB_PASS: "${DB_PASSWORD_PLATFORMDB}"

  fiwareManager:
    image:
      tag: "${TAG_FIWARE_MANAGER}"
    config:
      MONGO_DB_HOST: "${MONGO_HOST}"
      MONGO_DB_PORT: "${MONGO_PORT}"
      # Archivo de la trama LIDAR. Sin OTE_ARCHIVE_ENABLED=true el endpoint responde
      # 200 y descarta la trama: es deliberado para que el sensor no reintente.
      OTE_ARCHIVE_ENABLED: "true"
      OTE_ARCHIVE_PREFIX: ote/incoming
      OTE_FLUSH_SECONDS: "60"
      OTE_FLUSH_MAX_BYTES: "4194304"
      OTE_MAX_BUFFER_BYTES: "209715200"
      STORAGE_TYPE: "${STORAGE_TYPE}"
      AWS_S3_BUCKET: "${S3_BUCKET}"
      AWS_S3_REGION: "${S3_REGION}"
      LOCAL_ENDPOINT: "${MINIO_ENDPOINT}"
      LOCAL_BUCKET: "${S3_BUCKET}"
      LOCAL_SECURE: "false"
    gatewayAPI:
      enabled: true
      routes:
        - httpsOnly: true
          route:
            gateway: "${GATEWAY_PUBLIC}"
            hostnames: ["${DOMAIN_FIWARE}"]
            backendPort: 8000
    secrets:
      MONGO_DB_USERNAME: "${MONGO_USER}"
      MONGO_DB_PASSWORD: "${MONGO_PASSWORD}"
      # El endpoint LIDAR es público: sin este secreto compartido acepta a cualquiera.
      OTE_WEBHOOK_TOKEN: "${OTE_WEBHOOK_TOKEN}"
      AWS_S3_ACCESS_ID: "${S3_ACCESS_KEY}"
      AWS_S3_SECRET_KEY: "${S3_SECRET_KEY}"
      LOCAL_ACCESS_ID: "${MINIO_ACCESS_KEY}"
      LOCAL_SECRET_KEY: "${MINIO_SECRET_KEY}"

  iotAgentJson:
    config:
      IOTA_JSON_LD_CONTEXT: "${CONTEXT_URL}"
      IOTA_MONGO_HOST: "${MONGO_HOST}"
      IOTA_MONGO_PORT: "${MONGO_PORT}"
    secrets:
      IOTA_MONGO_USER: "${MONGO_USER}"
      IOTA_MONGO_PASSWORD: "${MONGO_PASSWORD}"

  orionLd:
    config:
      ORIONLD_MONGO_HOST: "${MONGO_HOST}"
      ORIONLD_MONGO_PORT: "${MONGO_PORT}"
      # Must be EMPTY on Orion-LD 1.4.0. Orion builds its Mongo URI as
      # mongodb://<user>:<pass>@<ORIONLD_MONGO_HOST>?<ORIONLD_MONGO_AUTH_SOURCE>
      # with no "/" before the "?", which the mongoc driver rejects outright:
      #   Unable to connect to mongo(...): Invalid host string in URI
      # Adding the slash to the host fixes mongoc but breaks the legacy C++
      # driver, which then parses the port as "27017/" and aborts. There is no
      # value of this variable that yields a valid URI for both drivers.
      # Left empty, the URI carries no database, and the driver defaults
      # authSource to admin — which is where the generator creates the user.
      ORIONLD_MONGO_AUTH_SOURCE: ""
    secrets:
      # Orion-LD authenticates with a Mongo user + password via these env vars —
      # the same fragmented host/port/user/password configuration the production
      # on-prem installs use. (The single -dbURI / ORIONLD_MONGO_URI form proved
      # unreliable, so it is intentionally not used here.)
      ORIONLD_MONGO_USER: "${MONGO_USER}"
      ORIONLD_MONGO_PASSWORD: "${MONGO_PASSWORD}"

  cbConsumer:
    image:
      tag: "${TAG_QUEUES_CONSUMER}"
    config:
      STORAGE_TYPE: "${STORAGE_TYPE}"
      AWS_S3_BUCKET: "${S3_BUCKET}"
      AWS_S3_REGION: "${S3_REGION}"
      AWS_S3_IMAGES_BUCKET: "${S3_BUCKET}"
      AWS_S3_IMAGES_REGION: "${S3_REGION}"
      LOCAL_ENDPOINT: "${MINIO_ENDPOINT}"
      LOCAL_BUCKET: "${S3_BUCKET}"
      LOCAL_IMAGES_ENDPOINT: "${MINIO_ENDPOINT}"
      LOCAL_IMAGES_BUCKET: "${S3_BUCKET}"
      DB_DATABASE: platformdb
      DB_HOST: "${PG_HOST}"
      DB_PORT: "${PG_PORT}"
      DB_REALTIME_HOST: "${PG_HOST}"
      DB_REALTIME_PORT: "${PG_PORT}"
      TS_DB_DATABASE: platform_ts
      TS_DB_HOST: "${PG_HOST}"
      TS_DB_PORT: "${PG_PORT}"
      KEYCLOAK_URL: http://keycloak:8080
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM}"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_SECURITY: "${RABBITMQ_SECURITY}"
      RABBITMQ_VHOST: "${RABBITMQ_VHOST}"
      RABBITMQ_CA_FILE_PATH: "${RABBITMQ_CA_FILE_PATH}"
    # El PEM lo aportas por fuera: este fichero se regenera en cada ejecucion del generador.
    rabbitmqCaSecret: "${RABBITMQ_CA_SECRET_CB_CONSUMER}"
    secrets:
      DB_USERNAME: platformdb
      DB_PASSWORD: "${DB_PASSWORD_PLATFORMDB}"
      # Valida la cabecera X-Queues-Consumer-Token de /publish (SEC-017).
      QUEUES_CONSUMER_API_TOKEN: "${QUEUES_CONSUMER_API_TOKEN}"
      TS_DB_USERNAME: platformdb
      TS_DB_PASSWORD: "${DB_PASSWORD_PLATFORMDB}"
      DB_REALTIME_USERNAME: realtime
      DB_REALTIME_PASSWORD: "${DB_PASSWORD_REALTIME}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
      KEYCLOAK_USER: "${KEYCLOAK_ADMIN_USER}"
      KEYCLOAK_PASSWORD: "${KC_ADMIN_PASSWORD}"
      AWS_S3_ACCESS_ID: "${S3_ACCESS_KEY}"
      AWS_S3_SECRET_KEY: "${S3_SECRET_KEY}"
      AWS_S3_IMAGES_ACCESS_ID: "${S3_ACCESS_KEY}"
      AWS_S3_IMAGES_SECRET_KEY: "${S3_SECRET_KEY}"
      LOCAL_ACCESS_ID: "${MINIO_ACCESS_KEY}"
      LOCAL_SECRET_KEY: "${MINIO_SECRET_KEY}"
      LOCAL_IMAGES_ACCESS_ID: "${MINIO_ACCESS_KEY}"
      LOCAL_IMAGES_SECRET_KEY: "${MINIO_SECRET_KEY}"

  genericConsumer:
    image:
      tag: "${TAG_QUEUES_CONSUMER}"
    config:
      STORAGE_TYPE: "${STORAGE_TYPE}"
      AWS_S3_BUCKET: "${S3_BUCKET}"
      AWS_S3_REGION: "${S3_REGION}"
      AWS_S3_IMAGES_BUCKET: "${S3_BUCKET}"
      AWS_S3_IMAGES_REGION: "${S3_REGION}"
      LOCAL_ENDPOINT: "${MINIO_ENDPOINT}"
      LOCAL_BUCKET: "${S3_BUCKET}"
      LOCAL_IMAGES_ENDPOINT: "${MINIO_ENDPOINT}"
      LOCAL_IMAGES_BUCKET: "${S3_BUCKET}"
      DB_DATABASE: platformdb
      DB_HOST: "${PG_HOST}"
      DB_PORT: "${PG_PORT}"
      DB_REALTIME_HOST: "${PG_HOST}"
      DB_REALTIME_PORT: "${PG_PORT}"
      TS_DB_DATABASE: platform_ts
      TS_DB_HOST: "${PG_HOST}"
      TS_DB_PORT: "${PG_PORT}"
      KEYCLOAK_URL: http://keycloak:8080
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM}"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_SECURITY: "${RABBITMQ_SECURITY}"
      RABBITMQ_VHOST: "${RABBITMQ_VHOST}"
      RABBITMQ_CA_FILE_PATH: "${RABBITMQ_CA_FILE_PATH}"
      WEB_FRONT_URL: "${URL_FRONTEND}"
    rabbitmqCaSecret: "${RABBITMQ_CA_SECRET_GENERIC_CONSUMER}"
    secrets:
      DB_USERNAME: platformdb
      DB_PASSWORD: "${DB_PASSWORD_PLATFORMDB}"
      # Valida la cabecera X-Queues-Consumer-Token de /publish (SEC-017).
      QUEUES_CONSUMER_API_TOKEN: "${QUEUES_CONSUMER_API_TOKEN}"
      TS_DB_USERNAME: platformdb
      TS_DB_PASSWORD: "${DB_PASSWORD_PLATFORMDB}"
      DB_REALTIME_USERNAME: realtime
      DB_REALTIME_PASSWORD: "${DB_PASSWORD_REALTIME}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
      KEYCLOAK_USER: "${KEYCLOAK_ADMIN_USER}"
      KEYCLOAK_PASSWORD: "${KC_ADMIN_PASSWORD}"
      AWS_S3_ACCESS_ID: "${S3_ACCESS_KEY}"
      AWS_S3_SECRET_KEY: "${S3_SECRET_KEY}"
      AWS_S3_IMAGES_ACCESS_ID: "${S3_ACCESS_KEY}"
      AWS_S3_IMAGES_SECRET_KEY: "${S3_SECRET_KEY}"
      LOCAL_ACCESS_ID: "${MINIO_ACCESS_KEY}"
      LOCAL_SECRET_KEY: "${MINIO_SECRET_KEY}"
      LOCAL_IMAGES_ACCESS_ID: "${MINIO_ACCESS_KEY}"
      LOCAL_IMAGES_SECRET_KEY: "${MINIO_SECRET_KEY}"

  carrot:
    image:
      tag: "${TAG_QUEUES_CONSUMER}"
    config:
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_SECURITY: "${RABBITMQ_SECURITY}"
      RABBITMQ_VHOST: "${RABBITMQ_VHOST}"
      RABBITMQ_CA_FILE_PATH: "${RABBITMQ_CA_FILE_PATH}"
    rabbitmqCaSecret: "${RABBITMQ_CA_SECRET_CARROT}"
    secrets:
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

  frontend:
    image:
      tag: "${TAG_FRONTEND}"
    config:
      API_BASE_URL: "${URL_API}"
      OIDC_URL: "${URL_KEYCLOAK}"
      OIDC_REALM: "${KEYCLOAK_REALM}"
      OIDC_CLIENT_ID: pid-gijon-client
      MAP_TILES_URL: "${MAP_TILES_URL}"
      MAP_TILES_ATTRIBUTION: "${MAP_TILES_ATTRIBUTION}"
      MAP_DEFAULT_CENTER: "${MAP_DEFAULT_CENTER}"
      MAP_DEFAULT_ZOOM: "${MAP_DEFAULT_ZOOM}"
    gatewayAPI:
      enabled: true
      routes:
        - httpsOnly: true
          route:
            gateway: "${GATEWAY_PUBLIC}"
            hostnames: ["${DOMAIN_FRONTEND}"]
            backendPort: 8080

  webBack:
    image:
      tag: "${TAG_WEB_BACK}"
    initContainers:
      - name: web-back-migrations
        # Bare repository name, like every other component: the chart prepends
        # global.imageRegistry. Never hardcode a registry path here — it would
        # resolve to <registry>/<path>/web-back and the pull would fail.
        image: web-back
        tag: "${TAG_WEB_BACK}"
        command: ["sh", "-c", "/var/www/html/migration.sh||true"]
    config:
      DB_DATABASE: platformdb
      DB_USERNAME: platformdb
      DB_HOST: "${PG_HOST}"
      DB_PORT: "${PG_PORT}"
      DB_REALTIME_HOST: "${PG_HOST}"
      DB_REALTIME_PORT: "${PG_PORT}"
      AWS_S3_BUCKET: "${S3_BUCKET}"
      AWS_S3_REGION: "${S3_REGION}"
      AWS_S3_IMAGES_BUCKET: "${S3_BUCKET}"
      AWS_S3_IMAGES_REGION: "${S3_REGION}"
      AWS_ENDPOINT: "${STORAGE_ENDPOINT}"
      AWS_USE_PATH_STYLE_ENDPOINT: "${STORAGE_PATH_STYLE}"
      FRONTEND_URL: "${URL_FRONTEND}"
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REDIRECT_URI: "${URL_KEYCLOAK}"
      # Redes de las que se aceptan las cabeceras X-Forwarded-*; recortala al CIDR de la
      # pasarela en config.env. Vacia = no confiar en ningun proxy.
      TRUSTED_PROXIES: "${TRUSTED_PROXIES}"
      KEYCLOAK_ALLOWED_CLIENTS: "${KEYCLOAK_ALLOWED_CLIENTS}"
      KC_IMPERSONATION_URL: http://keycloak:8080
      KC_IMPERSONATION_CLIENT_ID: "${KEYCLOAK_PUBLIC_CLIENT}"
    gatewayAPI:
      enabled: true
      routes:
        - httpsOnly: true
          route:
            gateway: "${GATEWAY_PUBLIC}"
            hostnames: ["${DOMAIN_API}"]
            backendPort: 80
    secrets:
      DB_PASSWORD: "${DB_PASSWORD_PLATFORMDB}"
      DB_REALTIME_USERNAME: realtime
      DB_REALTIME_PASSWORD: "${DB_PASSWORD_REALTIME}"
      APP_KEY: "${LARAVEL_APP_KEY}"
      # El backend firma sus POST /publish con este secreto (SEC-017).
      QUEUES_CONSUMER_API_TOKEN: "${QUEUES_CONSUMER_API_TOKEN}"
      FILE_ENCRYPTION_KEY: "${FILE_ENCRYPTION_KEY}"
      GENERIC_ENCRYPTION_KEY: "${GENERIC_ENCRYPTION_KEY}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      KEYCLOAK_ENCRYPTION_ALGORITHM: RS256
      KEYCLOAK_CLIENT_ID: laravel-backend
      KEYCLOAK_CLIENT_SECRET: "${KEYCLOAK_CLIENT_SECRET}"
      KEYCLOAK_PUBLIC_KEY: "${KEYCLOAK_PUBLIC_KEY}"
      KC_ADMIN_CLIENT: change-password-client
      KC_MASTER_REALM: master
      KC_ADMIN_USER: "${KEYCLOAK_ADMIN_USER}"
      KC_ADMIN_PASSWORD: "${KC_ADMIN_PASSWORD}"
      KC_IMPERSONATION_CLIENT_SECRET: "${KC_IMPERSONATION_CLIENT_SECRET}"
      KC_IMPERSONATION_USERNAME: "${KC_IMPERSONATION_USERNAME}"
      KC_IMPERSONATION_PASSWORD: "${KC_IMPERSONATION_PASSWORD}"
      # Sin esta clave los atributos cifrados se sirven sin descifrar (se registra y sigue).
      ENCRYPTION_ENTITIES_KEY: "${ENCRYPTION_ENTITIES_KEY}"
      # La usan los endpoints internos /api/internal/check-*-write-permission (APISIX).
      API_GATEWAY_SECRET: "${API_GATEWAY_SECRET}"
      AWS_S3_KEY: "${STORAGE_ACCESS_KEY}"
      AWS_S3_SECRET: "${STORAGE_SECRET_KEY}"
      AWS_S3_IMAGES_KEY: "${STORAGE_ACCESS_KEY}"
      AWS_S3_IMAGES_SECRET: "${STORAGE_SECRET_KEY}"

  keycloak:
    image:
      tag: "${TAG_KEYCLOAK}"
    config:
      # La URL PUBLICA de la API, no la interna del cluster. Obligatoria: el entrypoint de la
      # imagen aborta si falta.
      #
      # Es contraintuitivo y ya estuvo mal: BACKEND_URL no la usa Keycloak para hablar con el
      # backend, sino que se sustituye en el tema de login y acaba en `window.BACKEND_URL`, que
      # lee el NAVEGADOR (login/resources/js/dynamicLogo.js) para descargar el logotipo de la
      # organizacion. Con un nombre interno como `http://web-back:80` el navegador falla con
      # ERR_NAME_NOT_RESOLVED y el logotipo por organizacion no aparece nunca — sin ningun error
      # en el servidor. Ningun uso de esta variable es del lado servidor: buscar `backendUrl` en
      # keycloak/pidtheme lo confirma.
      BACKEND_URL: "${URL_API}"
      KC_DB_URL_HOST: "${PG_HOST}"
      KC_DB_URL_PORT: "${PG_PORT}"
      KC_HOSTNAME: "${URL_KEYCLOAK}"
      KC_HOSTNAME_ADMIN: "${URL_KEYCLOAK}"
      # Marca blanca del tema de login. Vacias no pasa nada: el entrypoint sustituye
      # entonces los violetas por defecto (`${KC_BRAND_PRIMARY:-#7D00F4}`), y la plantilla
      # descarta cualquier valor que no empiece por `#`.
      KC_BRAND_PRIMARY: "${KC_BRAND_PRIMARY}"
      KC_BRAND_SECONDARY: "${KC_BRAND_SECONDARY}"
      KC_BRAND_INDIGO: "${KC_BRAND_INDIGO}"
      KC_BRAND_LOGIN_IMAGE: "${KC_BRAND_LOGIN_IMAGE}"
    gatewayAPI:
      enabled: true
      routes:
        - httpsOnly: true
          route:
            gateway: "${GATEWAY_PUBLIC}"
            hostnames: ["${DOMAIN_KEYCLOAK}"]
            backendPort: 8080
    secrets:
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: "${DB_PASSWORD_KEYCLOAK}"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN_USER}"
      KEYCLOAK_ADMIN_PASSWORD: "${KC_ADMIN_PASSWORD}"
      # KC_LARAVEL_BACKEND_SECRET / KC_REALM_MANAGEMENT_SECRET are NOT generated
      # here: the realm import ships placeholders for them and the entrypoint
      # refuses to start without both. k3s-deploy.sh generates them once per
      # environment into environments/<name>/keycloak-secrets.env and passes
      # them with --set. Installing by hand, add them here yourself.

