# Generated by scripts/generate-env.sh for environment: ${PROJECT_NAME}
# DO NOT COMMIT — contains generated passwords.
cluster:
  replicas: 1
  persistence:
    storage: "8Gi"
    storageClass: ""

vhost:
  enabled: true
  name: "${RABBITMQ_VHOST}"

user:
  enabled: true

credentials:
  username: "${RABBITMQ_USER}"
  password: "${RABBITMQ_PASSWORD}"
