# Generated by scripts/generate-env.sh for environment: ${PROJECT_NAME}
# DO NOT COMMIT — contains generated passwords.
cluster:
  instances: 1
  storage:
    size: "50Gi"
    storageClass: ""

initScripts:
  passwords:
    platformdb: "${DB_PASSWORD_PLATFORMDB}"
    keycloak: "${DB_PASSWORD_KEYCLOAK}"
    realtime: "${DB_PASSWORD_REALTIME}"
    airflow: "${DB_PASSWORD_AIRFLOW}"
    geoportal: ""
