# =============================================================================
# PID Gijón verification suite configuration — generated by scripts/generate-env.sh
# =============================================================================
# Consumed by ./tests/run-tests.sh <environment-name>. Everything derivable from
# config.env is pre-filled; with default arguments you should not need to touch
# this file. DO NOT COMMIT — it contains the admin password.
# =============================================================================

# --- Public endpoints (derived from your DOMAIN_* settings) ------------------
API_URL=https://${DOMAIN_API}
FIWARE_MANAGER=https://${DOMAIN_FIWARE}
KEYCLOAK_URL=https://${DOMAIN_KEYCLOAK}
FRONTEND_URL=https://${DOMAIN_FRONTEND}
KEYCLOAK_REALM=${KEYCLOAK_REALM}

# --- Platform admin credentials ----------------------------------------------
# ADMIN_USERNAME defaults to the admin user the platform's Keycloak realm seeds
# on first install (override with TESTS_ADMIN_USERNAME in config.env). Its
# PASSWORD is set by that realm import / your Keycloak setup — it is NOT
# generated by this installer, so fill it in here before running login and the
# device-flow checks. Re-running generate-env.sh preserves whatever you put here.
ADMIN_USERNAME=${TESTS_ADMIN_USERNAME}
ADMIN_PASSWORD=${TESTS_ADMIN_PASSWORD}

# The management API has no login endpoint (sign-in is authorization code +
# PKCE against Keycloak), so the suite mints its admin token at Keycloak with
# the backend's confidential client. This is the same secret web-back uses; it
# is also in SECRETS.env.
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID_TESTS}
KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}

# --- Device data path ---------------------------------------------------------
# API key used by devices to push data (the "k" query parameter), specific to
# your installation's device-type configuration. Leave empty: the suite
# discovers it automatically — from the device API, then (with kubectl access)
# by reading the IoT Agent for the throwaway device it provisions. Only set it
# by hand if auto-discovery fails; see tests/README.md, "Obtaining DATA_API_KEY
# and TENANT". (Preserved across generate-env.sh re-runs.)
DATA_API_KEY=${TESTS_DATA_API_KEY}
# Device type used for the test device (standard installs: one_fiware).
DEVICE_TYPE=one_fiware
# Serial prefix for test devices (created and deleted by the suite).
# Serial de un dispositivo YA APROVISIONADO contra el que verificar el camino del dato.
# La API de gestión no expone el alta de dispositivos, así que la batería no puede
# crearse uno: sin este valor se saltan las etapas 5 y 6.
TEST_DEVICE_SERIAL=
# NGSI-LD tenant for timeseries queries. Leave empty to use the tenant the
# platform assigns to the test device (standard installs: libelium).
TENANT=${TESTS_TENANT}
# Treat the device data path as required (true, default): if no DATA_API_KEY can
# be resolved, those checks FAIL instead of skipping, so a "green" run really
# means the data path was verified. Set false to make them optional.
REQUIRE_DATA_PATH=true

# --- HTTP behaviour -------------------------------------------------------------
# New installs often use a self-signed gateway certificate, so TLS verification
# is off by default. Set to true once you serve a trusted certificate.
TLS_VERIFY=false
HTTP_TIMEOUT=15
# Async propagation budget for the eventually-consistent checks (entity update,
# timeseries persistence). Raise these if the platform is slow under load.
PROPAGATION_ATTEMPTS=8
PROPAGATION_INTERVAL_SECONDS=2.5

# --- Kubernetes scope ------------------------------------------------------------
# kubectl context to use for cluster-level checks and DATA_API_KEY discovery
# (empty = current context).
KUBE_CONTEXT=
PLATFORM_NAMESPACE=pid-gijon

# Which bundled data charts to check (false = you use an external/managed service).
CHECK_POSTGRES=${TESTS_CHECK_POSTGRES}
CHECK_MONGODB=${TESTS_CHECK_MONGODB}
CHECK_RABBITMQ=${TESTS_CHECK_RABBITMQ}
CHECK_MINIO=${TESTS_CHECK_MINIO}

# --- Airflow (optional add-on) ----------------------------------------------
# The Airflow stage (test_07) runs only when AIRFLOW_URL is set. It deploys a
# one-shot copy of the custom_iota_post DAG with kubectl cp, runs it once, and
# checks the IoT Agent provisioned the entity in Orion-LD — then deletes the DAG
# and Variables. Set these in config.env (TESTS_AIRFLOW_*) before generating, or
# edit here. URL/USERNAME/PASSWORD and the apikey/tenant are preserved on re-run.
AIRFLOW_URL=${TESTS_AIRFLOW_URL}
AIRFLOW_USERNAME=${TESTS_AIRFLOW_USERNAME}
AIRFLOW_PASSWORD=${TESTS_AIRFLOW_PASSWORD}
AIRFLOW_NAMESPACE=${TESTS_AIRFLOW_NAMESPACE}
# Values written as the DAG's Airflow Variables (and baked in as its fallbacks).
# apikey/tenant are required — the DAG POSTs with a service-group apikey to a
# tenant; there is no safe default. The IoT Agent URL is the in-cluster service.
AIRFLOW_VAR_IOTA_URL=${TESTS_AIRFLOW_IOTA_URL}
AIRFLOW_VAR_IOTA_APIKEY=${TESTS_AIRFLOW_IOTA_APIKEY}
AIRFLOW_VAR_DATAMODEL=${TESTS_AIRFLOW_DATAMODEL}
AIRFLOW_VAR_TENANT=${TESTS_AIRFLOW_TENANT}
AIRFLOW_VAR_SCOPE=${TESTS_AIRFLOW_SCOPE}
AIRFLOW_VAR_ENTITY_NAME=${TESTS_AIRFLOW_ENTITY_NAME}
