#!/usr/bin/env bash
# =============================================================================
# PID Gijón — platform verification suite runner
# =============================================================================
# Verifies that a deployed environment actually works: cluster
# workloads, gateway & routing, public endpoints, login, and the full IoT data
# path (device lifecycle + timeseries persistence). Prints a report that says
# what was checked, what failed, and how to fix it.
#
# Usage:
#   ./tests/run-tests.sh <environment-name> [extra pytest args]
#
# Examples:
#   ./tests/run-tests.sh prod                       # everything
#   ./tests/run-tests.sh prod -m "not kubernetes"   # API checks only (no kubectl)
#   ./tests/run-tests.sh prod -m kubernetes         # cluster checks only
#
# Configuration comes from environments/<name>/tests.env, generated by
# scripts/generate-env.sh. Python dependencies (pytest, requests) are installed
# automatically into tests/.venv on first run.
# =============================================================================

set -eo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'; NC='\033[0m'
info() { echo -e "${BLUE}[INFO]${NC} $1"; }
ok()   { echo -e "${GREEN}[OK]${NC} $1"; }
die()  { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

ENV_NAME="${1:-}"
[ -n "$ENV_NAME" ] || die "Usage: $0 <environment-name> [extra pytest args]   (e.g. $0 prod)"
shift

TESTS_ENV_FILE="${REPO_ROOT}/environments/${ENV_NAME}/tests.env"
if [ ! -f "$TESTS_ENV_FILE" ]; then
    if [ -d "${REPO_ROOT}/environments/${ENV_NAME}" ]; then
        die "environments/${ENV_NAME}/tests.env not found.
        Re-run ./scripts/generate-env.sh ${ENV_NAME} — it renders tests.env for existing environments too."
    fi
    die "Environment '${ENV_NAME}' does not exist. Create it first: ./scripts/generate-env.sh ${ENV_NAME}"
fi

# --- python environment ------------------------------------------------------
PYTHON="${PYTHON:-python3}"
command -v "$PYTHON" >/dev/null || die "python3 not found. Install Python 3.10+ to run the verification suite."

VENV_DIR="${SCRIPT_DIR}/.venv"
if [ ! -x "${VENV_DIR}/bin/python" ]; then
    info "Creating Python virtualenv in tests/.venv (first run only)..."
    if command -v uv >/dev/null; then
        (cd "$SCRIPT_DIR" && uv venv --quiet "$VENV_DIR")
    else
        "$PYTHON" -m venv "$VENV_DIR" || die "Could not create a virtualenv. On Debian/Ubuntu: apt-get install python3-venv"
    fi
fi

if ! "${VENV_DIR}/bin/python" -c "import pytest, requests" >/dev/null 2>&1; then
    info "Installing test dependencies (pytest, requests)..."
    if command -v uv >/dev/null; then
        uv pip install --quiet --python "${VENV_DIR}/bin/python" -r "${SCRIPT_DIR}/requirements.txt"
    else
        "${VENV_DIR}/bin/python" -m pip install --quiet --disable-pip-version-check -r "${SCRIPT_DIR}/requirements.txt"
    fi
fi

# --- load environment & run --------------------------------------------------
info "Verifying environment '${ENV_NAME}' (config: environments/${ENV_NAME}/tests.env)"
set -a
# shellcheck disable=SC1090
source "$TESTS_ENV_FILE"
set +a

cd "$SCRIPT_DIR"
exec "${VENV_DIR}/bin/python" -m pytest "$@"
