{{- include "mongodb.validateCredentials" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.credentials.username | quote }}
  password: {{ .Values.credentials.password | quote }}
