apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headless.name }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
